-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost
-- Tiempo de generación: 07-11-2019 a las 00:58:35
-- Versión del servidor: 5.7.27-0ubuntu0.19.04.1
-- Versión de PHP: 7.2.24-0ubuntu0.19.04.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `sf42`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `Fielddefinitionlang`
--

CREATE TABLE  IF NOT EXISTS `Fielddefinitionlang` (
  `language` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `code` decimal(5,0) NOT NULL,
  `name` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `abbreviation` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `definition` longtext COLLATE utf8_unicode_ci,
  `example` longtext COLLATE utf8_unicode_ci,
  `comment` longtext COLLATE utf8_unicode_ci,
  `uso` longtext COLLATE utf8_unicode_ci,
  `review` tinyint(1) DEFAULT NULL,
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Volcado de datos para la tabla `Fielddefinitionlang`
--

INSERT INTO `Fielddefinitionlang` (`language`, `code`, `name`, `abbreviation`, `definition`, `example`, `comment`, `uso`, `review`, `created`, `updated`) VALUES
('es', '1', 'Tipo de formación kárstica', 'Tipo de formación', 'Para aquellos tipos de fomaciones kársticas que no son cavidades, este campo indica qué tipo de formación kárstica es. Es mútuamente exclusivo con  8[Tipo de cavidad].', NULL, NULL, NULL, 0, '2017-08-14 13:49:27', '2019-07-30 06:39:01'),
('es', '2', 'Sumersión', 'dubb', 'El grado de sumersión de ÉSTA entrada. En blanco si la entrada nunca ha estado sumergida.', NULL, NULL, NULL, 0, '2017-08-14 13:52:27', '2019-08-14 22:37:40'),
('es', '3', 'Presencia de flujo', '', 'Descrive cómo de activa es ESTA entrada.', NULL, '(1) Una entrada es clasificada como \'seca\' sólo cuando NUNCA ha tenido actividad. (2) Las cavidades acuáticas no deberían ser clasificadas como \'activas\' a menos que contengan una corritente de vapor permanente o intermitente. Si el agua en ellas es del mar, deberan ser descritas bajo 2[Sumersión].', NULL, 0, '2017-08-14 13:57:10', '2017-08-14 14:01:54'),
('es', '4', 'Dirección del flujo', '', 'Describe la dirección del flujo en ESTA entrada si tiene actividad, de otra modo, dejar en blanco.', NULL, '(1) Un \'inflow-outflow\' es una entrada en la que en ocasiones, el flujo de vapor es hacia el interior y  en otras, hacia el exterior. No se una para describir una cavidad de paso con flujo hacia el interior en un extremo y flujo exterior en el otro: tal cavidad tiene dos elementos, flujo hacia el interior y flujo hacia el exterior. \r\n(2) Una cavidad inundada marina la califica normalmente como flujo hacia el interior-exterior ya que el término hace referencia al flujo de vapor.', NULL, 1, '2017-08-14 14:15:51', '2017-08-14 14:16:19'),
('es', '5', 'Flujo interno', '', 'Describe las condiciones de flujo dentro de la cavidad, si difieren de las condiciones de flujo en ESTA entrada, en otro caso dejar en blanco.', 'This field would be completed where a dry entrance led to an internal stream, or where an intermittently active entrance led to a permanent stream. A perennially active entrance would not have this field completed unless its stream was joining another independent stream inside the cave.', NULL, NULL, 0, '2017-08-14 14:18:56', '2017-08-14 14:18:57'),
('es', '6', 'Agua interna', '', 'Describe las condiciones del agua permanente interna en una cavidad si difieren de las condiciones del agua en ESTA entrada, en otro caso dejar en blanco.', NULL, NULL, NULL, 0, '2017-08-14 14:21:30', '2017-08-14 14:21:30'),
('es', '7', 'Tipo de roca', '', 'Describes the type(s) of rock in which the cave or karst feature is formed.\r\nDescribe el tipo(s) de roca que está forma la cavidad o formación karstica.', NULL, NULL, 'Si esta es una remota entrada a una cavidad y su tipo de roca es diferente del resto de la cavidad, entonces registre el tipo de roca respectivo contra esta entrada además.', 1, '2017-08-14 14:27:46', '2017-08-14 14:43:59'),
('es', '8', 'Tipo de cavidad', '', 'Describe el tipo(s) de cavidad, pero dejar en blanco si 1[Tipo de formación kárstica] tiene algún valor.', NULL, 'Uno u otro 8[Tipo de cavidad] o 1[Tipo de formación kárstica] debe de completarse para poder guardar un registro.', NULL, 0, '2017-08-14 14:50:24', '2017-08-14 14:50:24'),
('es', '9', 'Cantidad de entradas', '', 'La cantidad total de entradas a la cavidad, tanto si están numeradas como si no, incluyendo la actual.', NULL, 'Normalmente completado sólo para el registro principal de la cavidad y si hay más que una entrada.', NULL, 0, '2017-08-14 14:59:57', '2017-08-14 14:59:57'),
('es', '10', 'Tipo de entrada', '', 'Se identifica si esta entrada es de tipo vertical o no, ignorando cualquier efecto intrascendiente debido al derrumbamiento en la entrada inmediata al área.', NULL, NULL, NULL, 0, '2017-08-14 15:10:16', '2017-08-14 15:10:16'),
('es', '11', 'Desarrollo', '', 'Palabras claves relacionadas con el desarrollo de la cueva o formación kárstica, y secuenciado de modo que el resultado sea una frase razonablemente legible.', NULL, 'Este no es un intento de sustituir una descripción de la cavidad o formación kárstica, sino de proporcionar un número finito de términos para búsquedas de desarrollo. Desde luego, el resultado es también una especie de descripción.\r\n This is not intended to replace a description of the cave or karst feature, but to provide a finite number of terms for development searches. Of course the result is also a kind of description.', '(1) The same word can be used more than once. (2) A \'through-cave\' should be noted using this field. (3) A suggested method is to scan the list of available terms a few times to become more familiar with it, assess the significant aspects of the cave\'s development, construct a brief statement, write the code numbers against each word, and when OK, transfer the code numbers into the computer in the correct sequence.', 0, '2017-08-14 15:24:56', '2017-08-14 15:24:56'),
('es', '12', 'Decoración', '', 'El grado de decoración o depositos secundarios (espeleotemas) en la cavidad.', NULL, NULL, NULL, 0, '2017-08-14 15:26:21', '2017-08-14 15:26:21'),
('es', '13', 'Temperatura mínima', '', 'La temperatura mínima del aire conocida existente en la cavidad, expresada en grados Celsius (pero omitiendo el símbolo de grados).', NULL, 'Este campo obviamente es demasiado simple para servir como una declaración científica adecuada de la temperatura mínima de una cavidad. Su objetivo es de dar una guía aproximada y permitir a la comparación/búsqueda/clasificación preliminar sobre la base de la temperatura.', NULL, 0, '2017-08-14 15:29:49', '2017-08-14 15:29:49'),
('es', '14', 'Temperatura máxima', '', 'La temperatura máxima del aire conocida existente en la cavidad, expresada en grados Celsius (pero omitiendo el símbolo de grados).', NULL, 'Ver comentario en 13[Temperatura mínima].', NULL, 0, '2017-08-14 15:30:35', '2017-08-14 15:31:40'),
('es', '15', 'Humedad mínima', '', 'El porcentaje de humedad mínima\r\nconocida existente en la cavidad.', NULL, 'Este campo obviamente es demasiado simple para servir como una declaración científica adecuada de la temperatura mínima de una cavidad. Su objetivo es de dar una guía aproximada y permitir a la comparación/búsqueda/clasificación preliminar sobre la base de la humedad.', NULL, 0, '2017-08-14 15:33:21', '2017-08-14 15:33:22'),
('es', '16', 'Humedad máxima', '', 'El porcentaje de humedad máxima conocida existente en la cavidad.', NULL, 'Ver comentario en 15[Humedad mínima].', NULL, 0, '2017-08-14 15:34:23', '2017-08-14 15:34:23'),
('es', '17', 'Nivel de agua', '', 'Una guía sobre la cantidad de agua o  cómo de seca es la cavidad en su totalidad.', NULL, NULL, 'Si áreas importantes de la cavidad difieren de esta media, entonces elegir \'rango de humedad amplio\'.', 0, '2017-08-14 15:53:19', '2017-08-15 06:04:04'),
('es', '18', 'CCAA en número de cavidad', '', 'El componente de la cavidad o formación kárstica que determina la CCAA (Estado) en la cual se considera que la cavidad se encuentra localizada.', NULL, NULL, '(1) En algunos casos una cavidad puede extenderse sobre el borde de una división administrativa 1. Esto es una materia para la política local decidir que Declaran que la cueva, como se considera, está en, y si más lejos encanta, como se considera, está en el mismo Estado o en su Estado real, para objetivos de número de cueva. Los 53 [Comentarios] el campo también pueden ser usados indicar su Estado real. Los campos de locational de la cueva o entradas desde luego mostrarían su posición real. (2) el código Estatal está lleno indirectamente vía la Consulta sobre 303 [la consulta de Área] (3) los códigos locales para los Estados de un país pueden ser puestos en 286 [el código Estatal], 287 [el nombre Estatal], y 354 [la abreviatura Estatal].', 1, '2017-08-14 16:00:25', '2017-08-15 09:55:44'),
('es', '19', 'Provincia en número de cavidad', '', 'El componente de la cavidad o formación kárstica que identifica la provincia (area o región administrativa 2 ) en la cual se considera que la cavidad se encuentra localizada, y es único dentro del código estatal superior.', NULL, 'En la elección de nuevos códigos de provincia, es mejor evitar usar las letras I u O ya que pueden provocar confusión con el número seriado adyacente , así como con cualquier código numérico de CCAA.', 'Los códigos de provincia se autocompletan mediante referencia a 303[Referencia a provincia].', 0, '2017-08-15 09:27:26', '2017-08-15 10:00:03'),
('es', '20', 'Penetrabilidad', '', 'Si la entrada es penetrable o no, incluyendo la entrada mediante buceo.', NULL, NULL, NULL, 0, '2017-08-15 10:41:30', '2017-08-15 10:41:30'),
('es', '21', 'Latitud - aproximada', '', 'La latitud dada sin ser tan exacta como la precisión especificada en 294 [Posición geogr. aproximada] para no revelar la posición exacta. Expresado como +/-grados decimales. Positivo si al norte o sobre el Ecuador, negativo si al sur del Ecuador.\r\nThe latitude given not closer than the precision specified in 294[Coarse - geogr. precision] in order not to reveal the exact location. Expressed as +/- degrees.decimal degrees. Positive if north of or on the Equator, negative if south of the Equator.', NULL, '(1) Expresado como un número real en lugar de grados:min simplifica las búsquedas basadas en localización, y geo-coding e sistemas  GIS. \r\n(2) Debido a que las refencias de rejilla son discontinuas en las zonas de rejilla limítrofes,  lat/longs son necesarias para permitir búsquedas en grandes extensiones. Permiten además encontrar la localización mediante el uso de un atlas ordinario. \r\n(3) Este campo está disponible cuando la latitud aproximada no está siendo auto-derivada de la latitud exacta en 245[Position - latitude]. \r\n(4) Longitud máxima del texto: signo(1)+entero(2)+sep(1)+dec(4)=total 8, scale 4.', NULL, 0, '2017-08-15 10:55:24', '2017-08-15 10:55:24'),
('es', '22', 'Longitud - aproximada', '', 'La latitud dada sin ser tan exacta como la precisión especificada en 294 [Posición geogr. aproximada] para no revelar la posición exacta. Expresado como +/-grados decimales. Positivo si al este o sobre el primer meridiano, negativo si al oeste de Greenwich o en meridiano 180 grados.', NULL, '(1) Véase comentarios en campo 21[Latitud - aproximada]. \r\n(2) Longitud máxima del texto: sign(1)+entero(3)+sep(1)+dec(4)= total 9, scale 4.', NULL, 0, '2017-08-15 10:59:15', '2017-08-15 10:59:54'),
('es', '23', 'Hoja del mapa - aproximado', '', 'El nombre oficial del mapa u hoja del mapa usada para dar una referencia a la rejilla aproximada para la cavidad o formación kárstica.', NULL, '(1) La serie a la cual este mapa pertenece se encuentra en 412[Serie de mapa - aproximada] normalmente en la tabla de Parámetros del Sitio.\r\n(2) Las localizaciones aproximadas están bien para su publicación, distribución, estudios, pero no lo suficiente buenas para localizar la cavidad.', NULL, 0, '2017-08-15 11:06:52', '2017-08-15 11:07:10'),
('es', '24', 'Hoja del mapa topo 100K', '', 'Reemplazada por 414[Map posn - nombre de mapa], normalmente encontrada en la tabla de referencias de la rejilla.', NULL, NULL, NULL, 0, '2017-08-15 11:12:38', '2017-08-15 11:12:38'),
('es', '25', 'Cualif.ref.rejilla - aprox.', '', 'Un valor usado para distinguir entre refencias a rejillas similares sobre una hoja de mapa, cuando se da la referencia aproximada a la rejilla para una cavidad.', NULL, 'La descripción de este cualificador de referencia de rejilla se da en  413[Cualif.ref.rejilla - aprox.], normalmente se encuentra en la tabla de parámetros del sitio.', NULL, 0, '2017-08-15 11:19:59', '2017-08-15 13:27:00'),
('es', '26', 'Rejilla de ref. - aprox.', '', 'La rejilla de referencia aproximada para ésta cavidad, dada sólo para la precisión acordada como adecuada para su publicación, pero aún razonable para análisis de distribución local.\r\nExpresada mediante el método descrito en la hoja de mapa respectiva, pero omitiendo dígitos para alcanzar la precisión aproximada requerida.', NULL, '(1) La precisión usada se define en 295[Precisión rej.ref. - aprox.] in the site parameters table. (2) Accurate grid refs can be recorded in 241[Map posn - map easting] etc.', NULL, 0, '2017-08-15 13:39:51', '2017-08-15 13:41:54'),
('es', '27', 'Localidad próxima', '', 'El nombre del pueblo, localidad o característica geográfica significativa cercana a la cavidad o formación kárstica.', NULL, NULL, 'Normalmente requerido sólo cuando la lat/long y rejilla de referencia no están disponibles.', 0, '2017-08-15 14:36:20', '2017-08-15 14:39:55'),
('es', '28', 'Altitud - aproximada', '', 'La altitud aproximada de esta entrada a la cavidad o formación kárstica, con una precisión adaptada para su publicación.', NULL, 'Las unidades de altitud se establecen en 446[Unidades de altitud - aproximado], y su precisión aproximada en 526[Precisión de altitud aproximada], ambas se encuentran normalmente en la tabla de parámetros del sitio.', NULL, 0, '2017-08-15 14:44:23', '2017-08-15 14:44:23'),
('es', '29', 'Grado de exploración', '', 'El grado en esta cavidad o formación karstica ha sido explorada.', NULL, NULL, 'Ya que los datos están siendo almacenados por entrada antes que por cavidad, este campo debería ser completado sólo para la cavidad.', 0, '2017-08-15 14:47:36', '2017-08-15 14:47:36'),
('es', '30', 'Tipo de descubrimiento', '', 'El tipo de evento que se están grabando sobre el descubrimiento original o similar sobre esta cavidad o formación kárstica.', 'Eventos disponibles: son cuando la cavidad fue encontrada, explorada o  grabada por primera vez.', NULL, '(1) Esta entrada es obligatoria si el descubridor o datos de fecha son completados. (2) Los campos de descubrimiento son multi-valued, por lo que varios eventos de descubrimiento y primera exploración pueden ser almacenados si se conocen.\r\n(3) El descubrimiento de posteriores extensiones pueden ser grabadas en el campo 35[Descubrimiento de extension].', 0, '2017-08-15 15:12:38', '2017-08-15 15:18:34'),
('es', '31', 'Nombre del descubridor', '', 'El nombre de la persona(as) y/o organización(es) que estuvieron envueltas en el evento original para la cavidad o formación karstica. Los formatos preferidos son apellidos, iniales(para personas), o iniciales sin puntos para organizaciones.', NULL, 'Idealmente, el valor de este campo se mostraría en pantalla como un enlace a 478[Person ID] o 380[Organisation ID] en las tablas para persona u organización. El campo \'nombres\' no sería necesario en la tabla  \'caves discovery\'.\r\nUn campo es necesario en la tabla de \'cavidades descubiertas\' sólo cuando el software de base de datos no permita tal enlace a la tabla de de Organizaciones o la Personas.', 'Normalmente puede necesitar introducir un valor aquí sólo si: \r\n- la información no fué autocompletada mediante un campo de búsqueda en Person o Organisation ID. \r\n- Los detalles de persona u organización no se encontraban disponibles en la tabla Person u Organisation en este sitio.', 1, '2017-08-15 15:27:06', '2017-08-15 15:42:51'),
('es', '32', 'Día de descubrimiento', '', 'Día del mes del respectivo evento de descubrimiento, en el rango 1-31.', NULL, NULL, 'Dejar en blanco si se desconoce.', 0, '2017-08-15 15:44:31', '2017-08-15 15:44:31'),
('es', '33', 'Mes de descubrimiento', '', 'El número del mes en el respectivo evento de descubrimiento, en el rango 1-12.', NULL, NULL, 'Dejar en blanco si se desconoce.', 0, '2017-08-15 15:45:58', '2017-08-15 15:46:17'),
('es', '34', 'Año de descubrimiento', '', 'El año, al completo, del evento de descubrimiento respectivo.', NULL, NULL, 'Dejar en blanco si se desconoce.', 0, '2017-08-15 15:47:26', '2017-08-15 15:47:26'),
('es', '35', 'Descubrimiento de extension', '', 'Información breve sobre el descubrimiento de una posterior extensión de una cavidad, incluyendo en nombre de la extensión, nombre del descubridor(es) y fecha.', '(1) Starburst Chamber: TCC, 26 Jan 1958. (2) Kelly\'s passage: Kelly J C & Downs X A, 13 June 1987.', NULL, 'Para extensiones múltiples, es mejor incluirlas en orden de fecha, empezando por la más antigua. \r\n(Editando el número de orden de secuencia para alterar el orden.)', 1, '2017-08-15 15:23:12', '2017-08-16 04:07:33'),
('es', '36', 'Fecha de descubrimiento', '', 'La fecha completa del respectivo evento de descubrimiento, en el formato de la base de datos.', NULL, NULL, 'Normalmento usado sólo cuando el campo del formato de fecha field is wanted. Note that this field can accept only fully specified dates.', 1, '2017-08-15 15:55:57', '2017-08-15 15:55:57'),
('es', '37', 'Nombre genero', '', 'El nombre del género de un espécimen biológico encontrado en la cavidad.', NULL, NULL, '(1) La precisión en la indentificación del género debe indicarse en 509[Nivel de confianza del género]. (2) El valor del género de debe introducir mediante un campo de búsqueda una tabla. Esto asegura que sólo se puedan introducir especies válidas, lo cual ayudará a posteriores búsquedas. Para alcanzar esto, la tabla de búsqueda en éste 37[Genus name] campo permite cargar tanto los valores de genero como los de especie, sin separar en otra tabla de búsqueda 38[Nombre especie], Escepto para anotaciones especiales sobre especie (Ver 38[Nombre especie] ayuda). \r\n(3) Si el sitio tiene además una base de datos de Espécies como parte del sistema, entonces Genero/Especie puede ser autocompletado mediante el campo 364[Especimen ID]. \r\n(4) Si un Genero/Especie no se encuentra en la tabla de búsqueda de Genero, Por favor, contacte con su administrador de la base de datos para que sea añadida.', 0, '2017-08-16 04:58:54', '2017-08-16 05:49:23'),
('es', '38', 'Nombre especie', '', 'El nombre de especie de un especimen biológico encontrado en la cavidad.', NULL, NULL, '(1) La precisión en la identificación de especies debería indicarse en el campo 510[Nivel de confianza especie]. (2) Si se conoce Genero pero no la especie , o, si es una nueva especie, entonces la notación correcta puede ser introducida cargando el campo Genero en la tabla de búsqueda Genero, entonces usaremos la tabla de búsqueda en éste campo 38[Nombre especie] para sobreescribir la especie con la notación correcta. (3) Si la especie deseada no se encuentra en la tabla de búsqueda Genero/Especie, porfavor, contacte con el administrador de la base de datos para que sea añadida.', 0, '2017-08-16 05:56:43', '2017-08-16 05:56:43'),
('es', '39', 'Especie ref - apellido', '', 'El apellido(s) e iniciales del autor(es) de una referencia describiendo la ocurrencia. en otro caso, el apellido e iniciales de la persona que identifica la ocurrencia de la especie en la cavidad,o el nombre de la perona poseedora de la colección. El formato para un autor debe ser:  \'apellidos, iniciales\'.', 'Brown, D.E. and McDougal, M.A.', NULL, 'Este campo sólo debería ser necesario si el valor no puede ser autocompletado mediante la búsqueda en el Article ID relevante en 263[Especies ref - articulo ID], o en un especimen en 364[Especimen ID].', 0, '2017-08-16 06:04:39', '2017-08-16 06:04:39'),
('es', '40', 'Importancia especie', '', 'Cualquier importancia especial  de esta ocurrencia de especie en la cavidad o formación kárstica pueda tener. Espresado como valor codificado.', NULL, NULL, 'Este campo sólo sería necesario completarlo normalmente si el valor no se mostrase o autocompletase mediante un enlace a Specimen ID relevante in 364[Specimen ID].', 0, '2017-08-17 02:26:24', '2017-08-17 02:26:33'),
('es', '41', 'Uso de la cavidad', '', 'El uso presente (si lo hay) de la cavidad, o de esta entrada si es una cavidad con entradas múltiples.', NULL, '\'Cavidad turística salvaje\' en el valor indica una cavidad la cual se encuetra más o menos en esteado salvaje sin trabajos de acondicionamiento añadidos para el turismo, pero se la considera como accesible para el público en general, en oposición a los espeleólogos, mediante algún medio de gestión de acceso o control.', NULL, 0, '2017-08-17 02:38:40', '2017-08-17 02:38:41'),
('es', '42', 'Tipo de propietario', '', 'La categoría de propietario para entrada en particular.', NULL, '(1) Una cavidad multi-entrada podría tener distintas categorías de propietarios. (2) La propiedad de espacios públicos normales debería ser establecida como \'govt owned\' - la frase \'community owned\' implica la posesión y control conjunta de una comunidad, y en general se aplica a una propiedad tribal.', NULL, 0, '2017-08-17 03:15:50', '2017-08-17 03:15:50'),
('es', '43', 'Daño', '', 'Tipos de daño presentes en la cavidad.', NULL, NULL, NULL, 0, '2017-08-17 03:16:24', '2017-08-17 03:16:25'),
('es', '44', 'Gestor de clasificación', '', 'Las iniciales comúnmente acordadas o abreviatura para la organización que tiene asignada la gestión de la clasificación de la cavidad.', NULL, NULL, '(1) Dejar en blanco si no está formalmente clasificada. (2) Obligatorio si 45[Management category] ha sido completado. (3) Si este campo es completado, entonces 45[Management category] también debe serlo.', 1, '2017-08-17 03:20:42', '2017-08-17 04:09:42'),
('es', '45', 'Management category', '', 'La categoría formal in la cual la cavidad o formación kárstica ha sido colocada por la autoridad gestora.', NULL, NULL, '(1) Si una cavidad tiene más de una clasificación, o diferentes pares de ella tienen distintas clasificaciones , entonces seleccionar \'multi-category\' y dar detalles en 53[Comentarios]. (2) Si se completa este campo, entonces 44[Management classifier] debe ser completado también.', 1, '2017-08-17 04:07:59', '2017-08-17 05:58:17'),
('es', '46', 'Métodos de protección', '', 'La situación o medidas que ayudan a la protección de la cavidad o formación kárstica.', NULL, NULL, '1. Si el acceso está sujeto a alguna forma de control, esta puede ser marcada en este campo y desarrollada en 258[Estado de acceso].', 0, '2017-08-17 06:01:56', '2017-08-17 06:01:56'),
('es', '47', 'Controlador', '', 'Las iniciales comúnmente conocidas de la organización controladora.', NULL, 'Normalmente omitido si se encuentra controlado por un propietario o gestor privado.', 'Si no es necesario un permiso de visita, introducir \'nobody\' (Véase pre-text, \'formulario de solicitud de acceso.)', 1, '2017-08-17 06:08:26', '2017-08-17 06:08:27'),
('es', '48', 'Importancias', '', 'Aspectos por los cuales esta cavidad o formación kárstica es importante, incluyendo el tipo(s) de estudios espefíficos de echos sobre la cavidad.', NULL, NULL, 'Si se han realizado estudios, inluirlos en la base de datos de referencias y referencias cruzadas a ellos mediante el campo 270[Artículo ID].', 1, '2017-08-17 06:11:30', '2017-08-17 06:49:47'),
('es', '49', 'Uso de la superficie', '', 'Uso actual de la superficie del terreno en el que se encuentra la entrada a la cavidad o formación kárstica.', NULL, NULL, NULL, 0, '2017-08-17 06:58:52', '2017-08-17 06:58:52'),
('es', '50', 'Dificultades', '', 'Equipo inusual, habilidades o actividades inevitables en una visita normal o exploración razonable de la cavidad, más que el llevar la cavidad hasta sus límites.', NULL, NULL, NULL, 0, '2017-08-17 07:44:41', '2017-08-17 07:44:41'),
('es', '51', 'Prospecciones', '', 'Indicaciones que apunten a la posibilidad de posteriores extensiones más allá de la cavidad conocida.', NULL, NULL, NULL, 0, '2017-08-17 07:49:28', '2017-08-17 07:52:00'),
('es', '52', 'Riesgos', '', 'Peligros que prodría encontrarse en algun lugar de la cavidad o formación kárstica.', NULL, NULL, NULL, 0, '2017-08-17 07:53:29', '2017-08-17 07:53:29'),
('es', '53', 'Comentarios', '', 'Línea de comentarios sobre la cavidad o formación kárstica.', NULL, NULL, '(1) Este campo debería usarse únicamente cuando un campo a medida más espefífico no esté disponible porque (1) los comentarios no puedan ser fácilmente mostrados en distintos idiomas, y (2) la información es difícil de usar en análisis y búsquedas. (2) Un uso válido de Comentarios es para qualificar una entrada en otro campo o para especificar el valor de un campo de selección que no estaba disponible. (3) Vada valor del campo es una línea de todos los comentarios. (4) Use punto y coma (;) entre comentarios separados.', 1, '2017-08-17 08:03:11', '2017-08-17 08:14:16'),
('es', '54', 'Porcentaje mapeado', '', 'El porcentaje aproximado de la extensión conocida de la cavidad que ha sido mapeado.', NULL, NULL, 'No incluye el símbolo de %.', 0, '2017-08-17 08:17:53', '2017-08-17 08:17:53'),
('es', '55', 'Código de organización', '', 'Las 3 letras estandar del código de organización que ha producido el mapa que está siendo referenciada en la cavidad o formación kárstica.', NULL, 'Véase Comentario en campo 264[Número de secuencia del mapa].', 'Necesitaría indicar este valor únicamente cuando: - No fue autocompletado mediante búsqueda en 265[ID mapa superior], o  - Los detalles del mapa no estaban disponibles en la base de datos del sítio.', 0, '2017-08-17 08:23:54', '2017-08-17 08:23:54'),
('es', '56', 'Longitud', '', 'La longitud acumulada de la cavidad o formación kárstica en metros.', NULL, NULL, '(1) El método usado se debe indicar en 57[Método de longitud]. \r\n(2) Las dimensiones que describan la extensión horizontal pueden ser introducidos en 67[Extensión a lo largo] y 68[Extensión a lo ancho]. \r\n(3) Cuando las cavidades se unan, o cuando hay más de una entrada numerada, la longitud total debería guardarse en el registro de la \'cavidad\' nominada, no en los registros de las entradas.', 1, '2017-08-18 08:38:24', '2017-08-18 08:38:25'),
('es', '57', 'Método longitud', NULL, 'El método utilizado para establecer la longitud de la cavidad o formación kárstica.', NULL, NULL, 'Este campo se debe usar siempre que 56[Longitud] haya sido completado, pero no si está vacío.', 0, '2017-08-18 08:46:58', '2017-08-23 10:34:49'),
('es', '58', 'Exactitud de longitud', 'Exactitud de longitud', 'La exactitud de la longitud total de una cavidad o formación kárstica, establecida en +/- metros.', 'Si la longitud se encuentra entre 510 y 520 metros, entonces la longitud se dará como 515 y el valor de este campo como 5, i.e. 515m +/-5m.', NULL, NULL, 1, '2017-08-22 09:59:33', '2017-08-22 09:59:33'),
('es', '59', 'Extensión bajo la entrada', 'Extensión bajo la entrada', 'La distancia vertical que se extiende bajo el punto más bajo de esta entrada, in metros.', NULL, NULL, '(1) Si sólo se conoce el rango vertical completo, o si es una formación kárstica, utilice 511[Extensión vertical] en lugar de este campo. (2) Si la entrada se encuentra en una formación kárstica, como una dolina, la entrada se tomará donde la cavidad  the entrance is taken to be where the cave leaves the profile of the karst feature. (3) If this field is completed, then 61[Vertical method] should be completed, and also 62[Vertical accuracy] if possible. (4) Any underwater depth, if known, should be included. The depth to the watertable can be shown in 53[Comments], e.g. \'wtable -50m;\'', 1, '2017-08-22 10:04:45', '2017-08-22 10:04:45'),
('es', '60', 'Extensión sobre la entrada', NULL, 'La distancia vertical de la cavidad que se extiende sobre el punto más bajo de la entrada, en metros.', NULL, NULL, 'Véase notas en 59[Extent below entrance].', 0, '2017-08-23 10:10:43', '2017-08-23 10:10:43'),
('es', '61', 'Método vertical', NULL, 'El método utilizado para establecer las dimensiones de la cavidad o formación kárstica.', NULL, NULL, 'Este campo siempre se debe completar si cualquiera de los campos para las  dimensiones verticales ha sido completado, pero no en otro caso.', 0, '2017-08-23 10:14:44', '2017-08-23 10:14:44'),
('es', '62', 'Precisión vertical', NULL, 'La precisión de la dimensiónes verticales establecidas de la cavidad o formación kárstica, establecidas en +/- metros.', 'Si el rango vertical se calculase o estimase entre 70 y 80 metros, el rango vertical debería establecerse como 75 y este campo como 5, i.e. 75m +/-5m.', NULL, NULL, 0, '2017-08-23 15:55:07', '2017-08-23 15:55:07'),
('es', '63', 'Longitud de la mayor sala', NULL, 'La longitud de la mayor sala de la cavidad, en metros.', NULL, NULL, 'Normalmente completado sólo para una sala de tamaño notable.', 0, '2017-08-24 09:29:51', '2017-08-24 09:29:52'),
('es', '64', 'Ancho de la mayor sala', NULL, 'El ancho de la mayor sala de la cavidad, en metros.', NULL, NULL, 'Normalmente completado sólo para una sala de tamaño notable.', 0, '2017-08-24 09:30:31', '2017-08-24 09:31:13'),
('es', '65', 'Altura de la mayor sala', NULL, 'La altura de la mayor sala de la cavidad, en metros.', NULL, NULL, 'Normalmente completado sólo para una sala de tamaño notable.', 0, '2017-08-24 09:32:21', '2017-08-24 09:32:21'),
('es', '66', 'Pendientes', NULL, 'Todas las longitudes de pendientes (no las longitudes de cuerda o  escaleras) en una cavidad, en metros, y listados nominalmente de forma sequencial desde el nivel superior al inferior.', NULL, NULL, NULL, 0, '2017-08-24 09:35:09', '2017-08-24 09:35:09'),
('es', '67', 'Extensión a lo largo', NULL, 'La extensión horizontal total máxima de una cavidad o formación kárstica, en metros, i.e. la distancia en línea recta entre sus puntos más lejanos.', NULL, 'En combinación con [Extensión a lo ancho] Conforma la extensión del rectángulo horizontal más pequeño que podría abarcar la cavidad o formación kárstica.', NULL, 0, '2017-08-24 10:06:16', '2017-08-24 14:21:35'),
('es', '68', 'Extensión a lo ancho', NULL, 'El ancho horizontal total máximo de una cavidad o formación kárstica, en metros, El ancho se mide en ángulo recto a la dirección a la dimensión guardada en 67[Extensión a lo largo].', NULL, 'Véase comentario en 67[Extensión a lo largo].', NULL, 0, '2017-08-24 14:20:33', '2017-08-24 14:22:09'),
('es', '69', 'Otros nombres', NULL, 'Nombres adicionales que la cavidad o formación kárstica tiene o ha tenido distintos del nombre actual dado en 70[Nombre principal], y expresado en el idioma local.', NULL, NULL, 'Véase notas de uso en 70[Nombre principal].', 0, '2017-08-24 14:24:48', '2017-08-24 14:24:48'),
('es', '70', 'Nombre principal', NULL, 'El nombre actual formalmente acordado para la cavidad o formación kárstica, expresado en el idioma local.', NULL, NULL, '(1) En la selección de nuevos nombres, tenga presente las directrices denominación local vigentes. (2) Cuando un nuevo nombre está esperando ratificación, enciérrelo con paréntesis. (3) Ya que el nombre almacenado Because this recorded name is probablemente se propagará, tome especial cuidado en almacenarlo con la ortografía y forma correcta. (4) Si desea la palabra \'cavidad\' o similar aparezca en el nombre, inclúyala en el campo.', 0, '2017-08-24 14:37:08', '2017-08-24 14:37:09'),
('es', '71', 'Ref - apellidos', NULL, 'El apellidos e inicales del autor(es) de una referencia que sea relevante para la cavidad o formación kárstica, expresado como \'apellido, iniciales\'.', '\'Smith, A.B., Brown, Y.L. & White, X.A.\', \'Smith, A.B.\', \'White, X.A. et al\'.', NULL, '(1) Normalmente sólo se necesita completar cuando los apellidos del autor  no pueden ser autocompletados mediante el campo de búsqueda en 270[Article ID]. (2) Si el artículo no existe todavía en la tabla Article, introduzca los apellidos manualmente. (3) Si son más de tres autores, únicamente introduzca el primer autor con inciales, más \'et al\'.', 0, '2017-08-24 14:43:31', '2017-08-24 14:43:32'),
('es', '72', 'Contenidos', NULL, 'Qué contiene la cavidad.', NULL, 'El propósito de este campo es ser la \'guía expresado llanamente\' sobre lo que se encuentra en la cavidad resumiendo cualquier entrada en campos científicos como 37[Nombre Genus], y listando cualquier otro elemento que no tenga una clasificación formal en el sistema.', '(1) Si se han creado entradas para algún campo \'científico\' , incluyalas en este cmpo además, ya que este campo resume TODOS los contenidos. (2) Si una entrada requerido no se encuentra en la lista de selección, introdúzcala en 53[Comentarios]. (3) El el caso de elementos sensibles, considere incluirlos en la base de datos pero señalando su nivel de seguridad en 467[Nivel de seguridad de datos] o suprimiento este campo en la impresión mediante 75[Lista de exclusiones de Cave FID].', 1, '2017-08-24 14:48:19', '2017-08-24 14:55:50'),
('es', '73', 'Valor sequencial', NULL, 'El número de valor secuencial de un registro entre otros que representa los valores de un campo de valores múltiples, que forma parte del campo clave de los registros.', 'Tres registros describiendo tres elementos diferentes representando los contenidos de una cavidad tendrían \'Valores sequenciales\' de of 1, 2, & 3 respectivamente.', 'El proposito de este campo es (1) hacer de campo clave de un registro único con valores múltiples, y (2) establecer la secuencia en la cual los campos de valor múltiple se almacenan y muestran.', NULL, 0, '2017-08-24 15:03:19', '2017-08-24 15:03:19'),
('es', '74', 'Serial referencia-cruzada', NULL, 'El número de serie componente del número para otras cavidades conectadas, entradas u otras formaciones kársticas.', NULL, NULL, '(1) El uso dependerá hasta cierto punto en cómo los números de cavidad o formación kárstica han sido usados, por ejemplo, si otras entradas a la cavidad tienen su própio número. Véase la \'Ayuda local\' Australiana para ejemplos de un método.', 1, '2017-08-24 15:06:26', '2017-08-24 15:10:42'),
('es', '75', 'Lista de exclusiones FID', NULL, 'Los FID de un campo para esta cavidad que ha de ser excluido de la impresión para un listado de cavidades.', NULL, '(1) Normalmente se debería a que el campo tiene el mismo valor para todas las cavidades en el área, y el valor puede por tanto ser cubierto para los propósitos de la lista en la Descripción del área. Como ejemplos pueden servir 7[Tipo de roca] o 42[propietario]. Sin embargo, cuando se trata de seguridad, véase 467[Nivel de seguridad de datos]', 'Introduzca el FID de cada campo para esta cavidad que contenga datos pero que no vayan a ser impresos en una lista de cavidades. La técnica es almacenar la mayoría de datos comunes en lugar de la entidad Región/Area, de forma que esta pueda aparecer en el área de notas, precediendo los detalles de la cavidad, y por tanto sin que sean impresos en los detalles de la cavidad.\r\nPara cualquier cavidad que sea una excepción a la norma para el área, se puede omitir la supresión de ese campo particular de forma que dichos datos distintos puedan imprimirse en listados individuales.\r\nSin embargo, tenga en cuenta que estos datos comunes aún DEBEN ser introducidos en cada cavidad. \r\nDe esta manera, los datos de cada cavidad están completos de forma individual, y la cavidad responderá corréctamente en búsquedas por esas características. Los campos que usualmente son candidatos para suprimirlos son: 7, 21, 22, 23, 414, 25, 26, 27, 28, 42, 49, 46, 47, 78, 13-16, 71/270, 76/431. \r\nLos campos que normalmente no deben ser suprimidos son: 18, 19, 77, 1, 69/70, 74, 9, 10/20/3/4/5/6, 11, 56, 57/58, 59/60/511, 61/62, 63/64/65, 66, 67/68, 52, 50, 29, 51.  \r\nEste campo debe ser reevaluado en cada actualización.', 0, '2017-08-24 15:16:24', '2017-08-25 04:47:50'),
('es', '76', 'Última actualización por', NULL, 'El nombre, apellidos, y organización de la persona que recientemente proveyó los datos de esta cavidad o formación kárstica para la actualización de la base de datos, junto con la fecha en que se suministró la información, en lugar de la fecha en que la información original fue generada.', NULL, '(1) Este campo estaría normalmente disponible para los usuarios para introducir el valor si el sistema de bases de datos no utiliza los campos disponibles para captura la información sobre cada actualización por lotes. (2) Normalmente este campo sería de solo lectura. (3) Una mejor alternativa a este campo sería el uso de 431[ID última actualización] que deriva de 421-424, el cual permite campos separados para Update ID, person, org, y date. (4) Para el proveedor de la información original en sí, véase 470[Proveedor de datos - person ID] y/o 471[Proveedor de datos - org ID] en los campos de Data Quality.', '(1) La información debe referirse únicamente a la última actualización, ya que el sistema guarda registro de actualizaciones previas. (2) Es una buena práctica cuando se obtienen actualizaciones particulares la revisión de otros datos de la cavidad para ver si son todavía correctos.', 0, '2017-08-24 15:39:35', '2017-08-25 05:49:56'),
('es', '77', 'Serial en número de cavidad', NULL, 'El componente del numero de cavidad, dentro del código de area acordado, que identifica la cavidad. Normalmente numérico. No se repite dentro del código de área. Justificado a la derecha si es numérico.', NULL, NULL, '(1) No incluir ningúna letra de sufijo  de la formación kárstica en el campo.', 0, '2017-08-24 15:40:28', '2017-08-25 06:24:07'),
('es', '78', 'Marcado de cavidad', NULL, 'El tipo de identificación marcada en esta entrada en particular o formación kárstica.', NULL, NULL, '(1) Si la marca no es la cavidad o número de entrada, sino otra marca identificativa como por ejemplo un estudio de superficie o exploración de superficie, seleccione los códigos 12-18, i.e. \'identificador\' antes que cavidad/número de entrada. (2) Si se encuentra más de un tipo de marca, seleccione la mejor.', 0, '2017-08-25 05:22:32', '2017-08-25 05:22:32'),
('es', '79', 'Título del informe', NULL, 'El título dado al informe de una salida o equivalente, publicado o sin publicar. Si el autor no ha dado título, el mantenedor de los registros puede dar una descripción nominal.', NULL, NULL, NULL, 0, '2017-08-25 05:26:18', '2017-08-25 05:26:18'),
('es', '80', 'Nombre de área', 'Nombre', 'El nombre acordado para una región o área kárstica.', NULL, NULL, NULL, 0, '2017-08-25 05:27:24', '2019-08-01 23:04:34'),
('fr', '80', 'Area name fr', NULL, 'The agreed name of a karst area or region. fr', NULL, NULL, NULL, 0, '2019-08-01 23:00:03', '2019-08-01 23:00:03'),
('es', '81', 'Código de área', NULL, 'El código alfabético de hasta 3 letras para designar una región o área kárstica. Normalmente emitido por la organización estatal espeleológica.', NULL, 'Aquí es donde el código es definido antes que usado.', NULL, 0, '2017-08-25 05:30:19', '2017-08-25 05:30:19'),
('es', '82', 'ID Campo corto estandar', NULL, 'El número de identificación internacional estandar para un campo de datos de cavidad/karst estandar. Siempre como entero. Emitodo únicamente por la base de datos maestra de la UIS.', NULL, '(1) Unlike normal data entities, standard field keys do not need to include country and organisation codes because they are generated only by a single master database. (2) Non-standard fields from other databases use keys which use principles similar to 227[Cave ID]. (3) If standard field keys are stored in the same database as non-standard fields, then they should be prefixed by AAUIS and their standard ID zero-filled to a width of 5 digits, e.g. in a foreign database, Field 34 should be stored as Field AAUIS00034.', NULL, 1, '2017-08-25 05:35:27', '2019-08-06 19:09:14'),
('es', '83', 'Id campo local', NULL, 'El ID de registro localmente utilizado por una organización para la definición de un campo usado por ella.', NULL, NULL, NULL, 0, '2017-08-25 06:26:26', '2017-08-25 06:26:26'),
('es', '84', 'Estado local de campo UIS', NULL, 'Para un campo que ha sido suministrado por UIS, este es el estado local independientemente del estado UIS.', NULL, NULL, NULL, 0, '2017-08-25 06:28:43', '2017-08-25 06:28:43'),
('es', '85', 'Tabla para valor establecido', NULL, 'El nombre de la tabla de la base de datos donde el valor para el campo respectivo ha sido establecido, en lugar de usado.', NULL, NULL, NULL, 0, '2017-08-25 06:32:44', '2017-08-25 06:33:34'),
('es', '86', 'Nombre de tabla maestra', NULL, 'El nombre de archivo para la tabla de base de datos maestra para una entidad.', 'Para la entidad Cave, el nombre del fichero de la tabla maestra en el sistema UISIC es CA0000.', NULL, NULL, 0, '2017-08-25 06:35:38', '2017-08-25 06:35:38'),
('es', '87', 'Longitud de campo textual', NULL, 'El máximo número de caracteres necesitados para contener cualquier posible valor que el campo pueda tener cuando su valor se expresa utilizando caracteres textuales.', 'Un campo numérico que tenga un rango de +/-10,000 con más de dos posiciones decimales, necesitaría 9 caracteres para asegurar que todos los valores pueden ser incluidos:  (signo(1) + dígitos numéricos completos(5) + separador decimal(1) + dígitos decimales(2) = total(9)). Un campo fecha puede requerir una longitud de campo de 10 para una representación textual: (dígitos del día(2) + separador día/mes(1) + dígitos del mes(2) + separador mes/año(1) + dígitos año(4) = total(10)).', 'Este campo no se necesita nunca cuando campos no textuales son convertidos a representación textual para la transferencia entre bases de datos.', NULL, 0, '2017-08-25 06:43:19', '2017-08-25 06:43:19'),
('es', '88', 'Excala del campo', NULL, 'El número de lugares decimales que requiere un campo numérico en particular.', NULL, NULL, NULL, 0, '2017-08-25 07:12:22', '2017-08-25 07:12:22'),
('es', '89', 'Posición de campo si fija', NULL, 'La posición del caracter para el inicio de un campo en particular cuando su tabla haya sido exportada a formato de texto de longitud fija.', NULL, '(1) Este sería usado normalmente en la preparación de la construcción de un fichero Karst Data Interchange (KDI). (2) Este valor variará de acuerdo al diseño de la base de datos usada en el sitio fuente específico.', NULL, 0, '2017-08-25 07:17:36', '2017-08-25 07:21:14'),
('es', '90', 'Campo sec si delimitado', NULL, 'La posición secuencial (1st, 2nd, 3rd, etc) de un campo particular cuando su tabla ha sido exportada formato de texto delimitado.', 'Si es el campo tercero, el valor sería \'3\'.', 'Como en 89[Posición de campo si fija].', NULL, 0, '2017-08-25 07:21:02', '2017-08-25 07:21:02'),
('es', '91', 'Tipo de longitud', NULL, 'Si el campo es de tipo \'largo\' o \'corto\'. Tipo largo es cuando el valor del campo puede ser bastante largo, entre una o más líneas, y puede contener caracteres delimitadores como comas, comillas, etc. Tipo corto es cuando la longitud es corta y limitada, y no contiene ningún caracter delimitador.', NULL, 'El principal propósito de este campo es ayudar en la escritura y lectura de ficheros de Karst Data Interchange.', 'Si hay alguna duda en cuanto a que el campo pueda contener caracteres delimitadores como comas, comillas, etc, seleccionar tipo \'largo\'.', 0, '2017-08-25 07:26:51', '2017-08-25 07:27:21'),
('es', '92', 'Tipo de dato', NULL, 'El tipo de dato para este campo, expresado como valor codificado.', NULL, NULL, NULL, 0, '2017-08-25 07:28:06', '2017-08-25 07:28:06'),
('es', '93', 'Tipo de codificación', NULL, 'El tipo de codificación, si la hay, usada como valor para los campos. Los valores para este campo son códigos numéricos.', NULL, NULL, NULL, 0, '2017-08-25 07:29:35', '2017-08-25 07:29:35'),
('es', '94', 'Secuencia SSC ID', NULL, 'El número de secuencia asignado a el SSC ID para este campo para para poner el campo en una secuencia conveniente cuando los campos se listan por SSC ID. Pueden ser modificados a placer para reordenar el orden del listado de campos.', NULL, NULL, NULL, 0, '2017-08-25 07:34:24', '2017-08-25 07:34:24'),
('es', '95', 'Valor simple o múltiple', NULL, 'Si el campo es de valor simple o múltiple, expresado como valor codificado.', NULL, NULL, NULL, 0, '2017-08-25 07:35:23', '2017-08-25 07:35:23'),
('es', '96', 'Estado UIS de campo UIS', NULL, 'Para una definición de campo emitido por UIS, este el el estado de la definición de UIS.', NULL, NULL, NULL, 0, '2017-08-25 07:36:50', '2017-08-25 07:37:21'),
('es', '100', 'Designación del campo local', NULL, 'La identificación local para un campo en el formulario de entrada de datos actual.', 'La designación local de ASF para 10[Tipo de entrada] es 8.1', 'El usuario es capaz de definir la equivalencia entre esta designación local actual y el ID estandar para el campo. Este permite un rango de formularios de entrada de datos personalizados con sus campos convenientemente identificados para una entrada de datos rápida, aún llamando al campo estandar correcto.', NULL, 0, '2017-08-25 07:45:10', '2017-08-25 07:45:26'),
('es', '101', 'Código de campo local', NULL, 'Cualquier identificación permanente usada por una organización para una definición del campo distinta de su registro ID de la base de datos.', NULL, NULL, NULL, 0, '2017-08-25 07:47:37', '2017-08-25 07:47:37'),
('es', '102', 'Nombre de campo - completo', NULL, 'El nombre de campo completo en inglés para un campo UIS.', NULL, NULL, NULL, 0, '2017-08-25 07:48:17', '2017-08-25 07:48:17'),
('es', '103', 'Nombre de campo - corto', NULL, 'El nombre de campo corto en inglés para un campo de la UIS.', '(1) Para su uso si el sistema de base de datos permite sólo nombres de campo cortos, e.g. dBase.', NULL, NULL, 0, '2017-08-25 07:50:06', '2017-08-25 07:50:06'),
('es', '111', 'Código de valor de campo', NULL, 'Este campo contiene los códigos permitidos que pueden ser introducidos en un campo de datos. Normalmente códigos estandar UIS.Un rango cerrado de valores existentes sin codificar  (e.g. nombres de hojas de mapas) no deben ser introducidos: en su lugar, deben ser incluidos en una tabla de búsqueda.', NULL, NULL, NULL, 0, '2017-08-25 07:54:06', '2017-08-25 07:54:06'),
('es', '112', 'Valor de traducción de campo', NULL, 'La traducción inglesa para un valor codificado usado en este campo.', NULL, NULL, NULL, 0, '2017-08-25 07:55:00', '2017-08-25 07:55:00'),
('es', '116', 'Campo también en tabla', NULL, 'Otra tabla en la cual aparezca este campo, aparte de la tabla donde su valor es establecido (campo 85).', NULL, NULL, NULL, 0, '2017-08-25 07:56:39', '2017-08-25 07:56:39'),
('es', '117', 'Valor usado o establec. aquí?', NULL, 'Si esta instancia del campo es para establecer/definir su valor, o para usar un valor establecido previamente en otro lugar. Esto podría ser el caso en el que la instancia fue \'clave ajena\', por ejemplo. Normalmente un campo se establecería en un solo lugar (Field 85), de forma que este campo se establecería normalmente como \'usado\'.', NULL, NULL, NULL, 0, '2017-08-25 08:01:08', '2017-08-25 08:01:08'),
('es', '132', 'Entity ID', NULL, 'El  identificador y clave de la base de datos para una entidad. Este consiste siempre en un único par de letras, elegidas para representar el nombre de la entidad de la forma más aproximada y en tantos idiomas como sea posible.', NULL, NULL, NULL, 0, '2017-09-22 11:04:14', '2017-09-22 11:04:16'),
('fr', '155', 'UIS status UIS fr', NULL, 'The English text for the UIS status of a field or value definition issued by UIS.', NULL, NULL, NULL, 0, '2019-07-30 19:19:47', '2019-07-30 19:19:47'),
('es', '177', 'Org ID - temporal', NULL, 'Un ID de registro temporal de la base de datos para una organización. Construido con los mismos pincipios del campo 227[Cave ID], pro usando las tres letras del Código de Organización del sitio donde está siendo introducida, en oposición de la organización que está siendo descrita.', NULL, '(1) Usado normalmente cuando una persona está introduciendo su nombre de organización en la base de datos en respuesta a una pregunta, pero no es la organización operando la base de datos del sitio que se está usando en ese momento. (2) El código para la organización puede no ser conocido, por lo tanto el código para el sitio actual se usa para para identificar el registro provisional. (3) Este ID y los detalles de la organización asociada son almacenados en una tabla separada a las tablas principales de Organizaciones.\r\n (4) Finalmente la organización tendrá asignado un ID formal permanente y su registro temporal será eliminado.', NULL, 1, '2017-08-31 10:31:44', '2017-08-31 10:31:45'),
('es', '201', 'Número de secuencia del mapa', '', 'El número de secuencia del mapa usado por la organización que emitió el número del mapa.', NULL, 'Este podría ser o no el mismo que el de la organización que produce el mapa, e.g. un club de espeleología numerando un mapa de cavidad guvernamental. El productor del mapa puede ser almacenado en 200[Fuente del mapa - cod. org.].', NULL, 0, '2017-08-17 08:59:28', '2017-08-17 08:59:28'),
('es', '258', 'Estado de acceso', '', 'La situción de acuerdo a cualquier restricción en el acceso a la cavidad.', NULL, NULL, '1. Este campo permite describir cualquier restricción de acceso maracada en 46[Métodos de protección].', 0, '2017-08-17 06:04:44', '2017-08-17 06:04:44'),
('es', '263', 'Especies ref - artículo ID', '', 'El Article ID interno en la base de datos de Articulo en referencia a especies para for a reference for a species occurrence in the cave.', NULL, NULL, 'If an Articles database is part of the system, this field would be auto-filled by a lookup on the Articles database. This lookup might also auto-fill other nearby Species Ref fields.', 0, '2017-08-16 06:04:58', '2017-08-16 06:51:15');
INSERT INTO `Fielddefinitionlang` (`language`, `code`, `name`, `abbreviation`, `definition`, `example`, `comment`, `uso`, `review`, `created`, `updated`) VALUES
('es', '264', 'Número de secuencia del mapa', '', 'La parte del número serie de este número de cavidad, que el mapa está referenciando para esta cavidad o formación kárstica.', 'Para el número de mapa de la cavidad Australiana 3B-16 igual a AU3B16.VSA245, Este campo sería \'245\', el número de serie del mapa.', '(1) Este campo de la base de datos refleja el valor del campo 201[Número de secuencia del mapa] en la base de datos (2) Idealmente el valor de este campo se mostraría en pantalla mediante un enlace a 201[Número de secuencia del mapa] en la base de dastos del mapa, mediante el campo ID del mapa. \r\n\r\nEl campo [Número de secuencia del mapa] podría no ser necesario entonces en esta tabla \'Mapa superior\' en la base de datos de cavidades. \r\n\r\nSe necesita un campo efectivo en la base de datos de cavidades sólo si el software no permite tal enlace a la base de datos del mapa.\r\n\r\n(3)  El campo debería ser justificado a la derecha para permitir su ordenación\r\n- este es un campo alfanumérico más que numérico para poder incluir letras si se desea.', 'Normalmente necesitará introducir un valor aquí sólo si: \r\n- La información no fue autocompletada mediante su búsqueda  en el ID del Mapa, o - los detalles del mapa no estaban disponibles en la base de datos del mapa de este sitio.', 1, '2017-08-17 08:42:39', '2017-08-17 08:54:07'),
('es', '265', 'ID mapa superior', '', 'El ID interno de la base de datos de un mapa que ha sido referenciado para dar una covertura extensiva de esta cavidad o formación kárstica, incluso no sea el mapa disponible más preciso de esta cavidad.', NULL, NULL, 'Si los detalles del mapa no han sido introducidos todavía en las tablas, entonces no estará disponible el ID para la búsqueda, por lo que, en su lugar. introducir los detalles del mapa en los campos inmediatos. Lo mismo en caso de que no exista base de datos de mapas en éste sitio.', 0, '2017-08-17 08:31:00', '2017-08-17 08:31:00'),
('es', '270', 'Artículo ID', '', 'El  ID de registro interno de la base de datos para una cita hecha en referencia a esta cavidad o formación kárstica. En blanco si el artículo aún no se encuentra en la base de datos pero los detalles están disponibles para crear la entrada en la bse de datos.', NULL, NULL, 'Este campo se autocompletaría normalmente mediante la búsqueda en la base de datos de Articles, la cual podría autocompletar al mismo tiempo otros campos de referencia a la cavidad en pantalla.', 0, '2017-08-17 06:56:12', '2017-08-17 06:56:12'),
('es', '279', 'Nombre de serie de mapas', 'Nombre', 'El nombre oficial de una Serie de Mapas', NULL, NULL, NULL, 0, '2019-07-31 00:47:19', '2019-07-31 00:47:19'),
('es', '295', 'Precisión rej.ref. - aprox.', '', 'La precisión según la cual las rejillas de referencia aproximadas, 26[Rejilla de referencia - aprox.], pueden ser dadas, usando las mismas unidades que las rejillas de referencia.', 'En Australia las rejillas de referencia proximadas se expresan con una precisión de 10 000 metros (10km). \r\nMáxima longitud del texto: sign(0)+entero(6)+sep(1)+dec(3) = total 10, scale 3.', 'Poseer coordenadas aproximadas disponibles permite la publicación de una localización aproximada para facilitar búsquedas espaciales e informes sin revelar la localización exacta. Este campo selecciona la precisión aproximada conveniente para rejillas de referencia en este país.', 'Este campo sólo puede ser establecido por el Administrador Central de la Base de Datos.', 0, '2017-08-15 13:41:22', '2017-08-15 13:51:58'),
('es', '303', 'Referencia a provincia', '', 'Campo auxiliar que permite utilizar una tabla de búsqueda para la provincia de la cavidad. Para hacerlo único, concatena códigos de pais+ccaa+provincia. Véase además 223[Designación de provincia], que es el campo de búsqueda para este campo.', NULL, NULL, NULL, 1, '2017-08-15 10:30:24', '2017-08-15 10:30:24'),
('es', '364', 'Specimen ID', '', 'El ID del registro interno de la base de datos en la tabla Specimen que corresponda a este especimen para esta cavidad o formación kárstica.', NULL, 'Esta es una clave interna de base de datos, como inequívoca de cualquier Specimen Number publicado.', 'Este campo sólo se autocompletaría normalmente mediante la búsqeda en la base de datos Specimen, el cual podría a su vez autocompletar otros campos de \'especies encontradas\'.', 0, '2017-08-17 02:31:23', '2017-08-17 02:31:23'),
('es', '393', 'Cobertura de la organización', NULL, 'La cobertura geográfica de una organización, expresada como valor codificado.', 'Códigos para nacional, estatal o local.', NULL, NULL, 0, '2019-08-28 14:12:02', '2019-08-28 14:12:02'),
('es', '412', 'Serie de mapa - aproximado', '', 'Una frase breve sobre la serie del mapa usada para proveer la hoja del mapa y referencia a la rejilla para localizaciones aproximadas.', '\'250K topo\' for 1:250 000 Topographic Series.', NULL, 'Este campo sólo puede ser establecido por el Administrador Central de la Base de Datos.', 0, '2017-08-15 11:10:13', '2017-08-15 11:10:13'),
('es', '413', 'Cualif.ref.rejilla - aprox.', '', 'Una frase breve describiendo el cualificador que está siendo utilizado, que permita distinguir \r\nentre refencias de rejilla similares en la hoja de un mapa cuando se dan localizaciones aproximadas.', '\'número de hoja del mapa 100k\'', '(1) En hojas 250K puede usar \'Letra de caudrícula 100km\' o el  \'número de hoja 100K\' para distinguir entre refencias a la rejilla idénticas en la hoja.', 'Este campo puede ser establecido sólamente por el Administrador Central de la Base de Datos.', 0, '2017-08-15 11:20:52', '2017-08-15 11:31:04'),
('es', '431', 'Latest update ID', NULL, 'El ID interno de la DB de la actualización por lotes más reciente aplicada a esta cavidad.', NULL, '(1) Este campo no se completa normalmente por el usuario, sino que es actualizada automáticamente cuando se realiza una actualización por lotes. (2) Existen campos similares para otras entidades, como Map.', NULL, 0, '2017-08-25 04:57:45', '2017-08-25 04:57:47'),
('es', '465', 'Tipo de fuente de datos]', NULL, 'El tipo de fuente de la cual se han obtenido el valor de los datos, atendiendo a cómo de cercanos o lejanos son respecto a los datos originales fue el proveedor, expresado mediante un valor codificado en 470[Proveedor de datos - person ID] o la orgnización identificada en 471[Proveedor de datos - org ID].', 'Esta debería ser información de primera mano para esa persona, o debería haber sido obtenida de una publicación.', NULL, NULL, 1, '2017-08-25 05:07:08', '2017-08-25 05:08:21'),
('es', '467', 'Nivel de seguridad de datos', NULL, 'El grado que los valores de este dato puede ser difundido o publicado , expresado como un valor codificado.', NULL, NULL, NULL, 0, '2017-08-24 15:19:04', '2017-08-24 15:19:04'),
('es', '470', 'Proveedor de datos - person ID', NULL, 'El ID interno de la DB de la tabla Person que identifica la persona conocedora de los datos originales en los que se basa este valor.', NULL, 'Campo 465[Tipo de fuente de datos] muestra la relación de esta persona con los datos originales.', NULL, 0, '2017-08-25 05:02:17', '2017-08-25 05:08:46'),
('es', '471', 'Proveedor de datos - org ID', NULL, 'El ID del registro interno de la base de datos de la tabla Organisation que identifica la organización de la persona que proveyó la fuente original de la información en la cual se basa este campo.', NULL, NULL, NULL, 0, '2017-08-25 05:10:50', '2017-08-25 05:10:50'),
('es', '661', 'Método altitud', NULL, 'El método usado para determinar la altitud de esta cavidad o formación kárstica, expresado como valor codificado.', NULL, NULL, 'El campo asociado de Comentario puede usarse para extender sobre el método si se desea.', 0, '2017-08-23 10:37:23', '2017-08-23 10:37:23');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `Fielddefinitionlang`
--
ALTER TABLE `Fielddefinitionlang`
  ADD PRIMARY KEY (`code`,`language`),
  ADD KEY `IDX_6812893377153098` (`code`);

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `Fielddefinitionlang`
--
ALTER TABLE `Fielddefinitionlang`
  ADD CONSTRAINT `FK_6812893377153098` FOREIGN KEY (`code`) REFERENCES `Fielddefinition` (`code`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
